### ISSUE TITLE
[MC-Version] 1.19 Fabric

### ISSUE THREAD

**Issue by The-Nyla** [MC-U-Team/Music-Player-Fabric#27]
### Detailed description of the feature

Just wondering if 1.19 fabric will be released

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Duplicate of #24

**Comment by The-Nyla** [comment]
Sorry I was on the forge GitHub page and forgot I had already made an issue on the fabric page, and forgot that the fabric version was a separate page
